// Generated by Supabase MCP `generate_typescript_types` for project
// jitfsxwsodocjikaobdu. Do not edit by hand — regenerate after schema changes.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  __InternalSupabase: {
    PostgrestVersion: '14.5';
  };
  public: {
    Tables: {
      subtasks: {
        Row: {
          created_at: string;
          done: boolean;
          id: string;
          sort_order: number;
          task_id: string;
          text: string;
          user_id: string;
        };
        Insert: {
          created_at?: string;
          done?: boolean;
          id?: string;
          sort_order?: number;
          task_id: string;
          text: string;
          user_id: string;
        };
        Update: {
          created_at?: string;
          done?: boolean;
          id?: string;
          sort_order?: number;
          task_id?: string;
          text?: string;
          user_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'subtasks_task_id_fkey';
            columns: ['task_id'];
            isOneToOne: false;
            referencedRelation: 'tasks';
            referencedColumns: ['id'];
          },
        ];
      };
      tasks: {
        Row: {
          category: string;
          created_at: string;
          done: boolean;
          due: string | null;
          id: string;
          notes: string;
          priority: string;
          sort_order: number;
          starred: boolean;
          title: string;
          updated_at: string;
          user_id: string;
        };
        Insert: {
          category?: string;
          created_at?: string;
          done?: boolean;
          due?: string | null;
          id?: string;
          notes?: string;
          priority?: string;
          sort_order?: number;
          starred?: boolean;
          title: string;
          updated_at?: string;
          user_id: string;
        };
        Update: {
          category?: string;
          created_at?: string;
          done?: boolean;
          due?: string | null;
          id?: string;
          notes?: string;
          priority?: string;
          sort_order?: number;
          starred?: boolean;
          title?: string;
          updated_at?: string;
          user_id?: string;
        };
        Relationships: [];
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      [_ in never]: never;
    };
    Enums: {
      [_ in never]: never;
    };
    CompositeTypes: {
      [_ in never]: never;
    };
  };
};
